---
- name: Ensure old LVs, filesystems, and fstab entries are removed
  ansible.builtin.include_role:
    name: linux-system-roles.storage
  vars:
    # This section finds the mount points, unmounts them,
    # and removes them from /etc/fstab.
    storage_mounts:
      - path: /rhel_inst
        state: absent
      - path: /tivoli_inst
        state: absent
      - path: /tivoli
        state: absent

    # This section removes the Logical Volumes themselves
    # from the 'rootvg' pool.
    storage_volumes:
      - name: lv_inst
        pool: rootvg
        state: absent
      - name: lv_tivoli
        pool: rootvg
        state: absen