---
- name: Ensure old filesystems are unmounted
  ansible.posix.mount:
    path: "{{ item }}"
    state: absent
  with_items:
    - /rhel_inst
    - /tivoli_inst
    - /tivoli

- name: Remove old LVs from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^{{ item }}'
    state: absent
  with_items:
    - /dev/rootvg/lv_tivoli
    - /dev/rootvg/lv_inst

- name: Remove old LVs from rootvg
  community.general.lvol:
    vg: rootvg
    lv: "{{ item }}"
    state: absent
    force: true # Equivalent to lvremove -f
  with_items:
    - lv_inst
    - lv_tivoli