---
- name: Set elevator=noop in GRUB default
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=".*)"$'
    line: '\1 elevator=noop"'
    backrefs: yes
  register: grub_config

- name: Rebuild grub.cfg
  ansible.builtin.command:
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_config.changed