---
# rh_os_hardening/tasks/02_services.yml

# - name: 02_services | Ensure baseline services are enabled and running
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: started
#     enabled: true
#   loop: "{{ rh_os_hardening_services_ensure_running }}"

- name: 02_services | Disable default list of insecure services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ rh_os_hardening_services_disable_default }}"
  when: ansible_facts['os_family'] == 'RedHat'
  ignore_errors: true # A service might not be installed, which is OK

- name: 02_services | Disable NFS services (if requested)
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ rh_os_hardening_services_disable_nfs }}"
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - nfs_enabled | bool
  ignore_errors: true

- name: Ensure default systemd target is multi-user on RHEL 7.2
  ansible.builtin.file:
    src: /usr/lib/systemd/system/multi-user.target # The target file
    dest: /etc/systemd/system/default.target     # The symlink to manage
    state: link                                    # Ensure it's a symlink
    force: true                                    # Overwrite if it exists and isn't correct
  when: ansible_distribution_version == '7.2'